In [15]:
# verify installation of required packages
import tensorflow as tf
import numpy as np
# Version check
print("Tensor Version", tf.__version__)

Tensor Version 2.20.0


In [16]:
#Creating and Printing Scalar Tensors

# Scalar tensor
scalar = tf.constant(10) # --- scaler value ---
print(scalar)

tf.Tensor(10, shape=(), dtype=int32)


In [17]:
# 1D tensor -- Vector tensor
vector = tf.constant([1, 2, 3, 4]) # --- vector values ---
print(vector)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [18]:
# 2D Tensor -- Matrix tensor
matrix = tf.constant([[1, 2], [3, 4]]) # --- matrix values ---
print(matrix)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [19]:
#Operations on Scalar Tensor

a = tf.constant(10)
b = tf.constant(5)
print("Addition:", tf.add(a, b))
print("Subtraction:", tf.subtract(a, b))
print("Multiplication:", tf.multiply(a, b))
print("Division:", tf.divide(a, b))

Addition: tf.Tensor(15, shape=(), dtype=int32)
Subtraction: tf.Tensor(5, shape=(), dtype=int32)
Multiplication: tf.Tensor(50, shape=(), dtype=int32)
Division: tf.Tensor(2.0, shape=(), dtype=float64)


In [20]:
# Operations on  Vector Tensor

a = tf.constant([10, 20, 30])
b = tf.constant([1, 2, 3])

print("Addition:", tf.add(a, b))
print("Subtraction:", tf.subtract(a, b))
print("Multiplication:", tf.multiply(a, b))
print("Division:", tf.divide(a, b))

Addition: tf.Tensor([11 22 33], shape=(3,), dtype=int32)
Subtraction: tf.Tensor([ 9 18 27], shape=(3,), dtype=int32)
Multiplication: tf.Tensor([10 40 90], shape=(3,), dtype=int32)
Division: tf.Tensor([10. 10. 10.], shape=(3,), dtype=float64)


In [21]:
# Operations on Matrix Tensor
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

print("Addition:", tf.add(a, b))
print("Subtraction:", tf.subtract(a, b))
print("Multiplication:", tf.multiply(a, b))
print("Division:", tf.divide(a, b))

Addition: tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Subtraction: tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
Multiplication: tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
Division: tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


In [22]:
#Data Types and Shape of Tensors

tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

print("Data Type:", tensor.dtype)
print("Shape:", tensor.shape)
print("Number of Dimensions:", tf.rank(tensor)) # rank of matrix
print("Number of Dimensions:", tensor.ndim) # dimensions of matrix

Data Type: <dtype: 'int32'>
Shape: (2, 3)
Number of Dimensions: tf.Tensor(2, shape=(), dtype=int32)
Number of Dimensions: 2
